language: csharp
mono: none
dotnet: 2.0.0
before_script:
  - chmod -R a+x publish
script:
  - dotnet restore
  - dotnet build ./Order.Service.sln
after_success:
  - ./publish/travis_on_success.sh
notifications:
  email:
    on_success: never
    on_failure: always